database_path = "./target/dev.db"
jwt_secret = "A very cool JWT secret."

[test]
categories = [
    "Task 1",
    "Task 2",
    "Task 3",
    "Task 4"
]

[execution]
runner_token = "correct horse battery staple"
build_command = ["sh", "-c", "echo 'Hello world!' && sleep 10"]
compile_command = ["bash", "-c", "echo '#!/usr/bin/env bash' > \"${@: -1}\" && echo 'echo \"Hello test!\"' >> \"${@: -1}\" && chmod +x \"${@: -1}\" && echo \"$*\" && echo -e \"\\n${@: -1}\" && cat \"${@: -1}\" && sleep 5"]
binary_arguments = ["--hello"]
build_timeout = "5m"
test_timeout = "10m"
local_repo_path = "target/repos"
reference_compiler_image = "ubuntu:latest"

[[teams]]
id = "admin_team"
display_name = "The admin team"
members = ["2e7d40f3e82822848fef2285aa511fd6d4ae169d8b5feab646e3aed403f3bad2"]

[[teams]]
id = "foobars"
display_name = "The foobar team"
members = []

[oidc]
client_id = "MZQOu3xu9lDvQLnyUbx9UaE48mQt23Mp56A6IBxW"
client_secret = "svLCpBVQvPHAQCmPNhWlCH5914cRvgwhR4mfki1KCI8asUX2y7L3bNPKpXLZOztW4gtp9uhzaeFLevtusoAjdzKCyThmHhmt4wxS4xQDKhstXKKHAUjYxjrG5SExED5G"
issuer_url = "http://localhost:9000/application/o/test-oidc/"
scopes = ["email", "openid", "profile", "offline_access"]
redirect_url = "http://localhost:5173/login/oidc-callback"

#[github]
#status_check_interval = "10s"
#workflow_check_interval = "5m"
#app_name = "crow-test"
#app_id = 12345678
#workflow_path = ".github/workflows/crow.yml"
#workflow_template = """
#name: Crow workflow integration
#on:
#  push:
#    branches:
#      - main
#      - master
#  pull_request:
#
#jobs:
#  trigger-crow:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set start / end commit for pushes
#        if: github.event_name == 'push'
#        run: |
#          echo "BEFORE=${{ github.event.before }}" >> $GITHUB_ENV
#          echo "AFTER=${{ github.event.after }}" >> $GITHUB_ENV
#      - name: Set start / end commit for pull requests
#        if: github.event_name == 'pull_request'
#        run: |
#          echo "BEFORE=origin/$GITHUB_BASE_REF" >> $GITHUB_ENV
#          echo "AFTER=HEAD" >> $GITHUB_ENV
#      - name: Triggering crow
#        run: |
#          set -euxo pipefail
#          # This does not work for force-pushes (as before is no longer part of the branch!)
#          for sha in $(git rev-list "$BEFORE".."$AFTER"); do
#            echo "Would push sha $sha with auth ${{ secrets.CROW_INTEGRATION_TOKEN }}"
#            #curl --header 'Authorization: Bearer ${{ secrets.CROW_INTEGRATION_TOKEN }}' http://localhost:3000/integration/token/task/"$sha"
#          done
#      - name: Explaining a bit
#        run: |
#          echo "The commits were pushed in the crow queue."
#          echo "Crow periodically syncs the status from its queue to your repository, so a check should appear here soon :)"
#"""
#app_private_key = ""
