name: "Build and push docker image"
on:
  push:
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: compiler.vads.kastel.kit.edu
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: nix build .#docker.frontend
    - run: |
        echo "IMG_FRONTEND=$(docker load --quiet < result | sed -E 's/.+?: (.+)/\1/g')" >> $GITHUB_ENV
    - run: nix build .#docker.backend
    - run: |
        echo "IMG_BACKEND=$(docker load --quiet < result | sed -E 's/.+?: (.+)/\1/g')" >> $GITHUB_ENV
    - run: |
        docker tag "$IMG_FRONTEND" compiler.vads.kastel.kit.edu/crow-frontend:latest
        docker tag "$IMG_FRONTEND" compiler.vads.kastel.kit.edu/crow-frontend:$GITHUB_SHA
        docker rmi "$IMG_FRONTEND"
        docker push --all-tags compiler.vads.kastel.kit.edu/crow-frontend

        docker tag "$IMG_BACKEND" compiler.vads.kastel.kit.edu/crow-backend:latest
        docker tag "$IMG_BACKEND" compiler.vads.kastel.kit.edu/crow-backend:$GITHUB_SHA
        docker rmi "$IMG_BACKEND"
        docker push --all-tags compiler.vads.kastel.kit.edu/crow-backend
